{"id": "LgWIGXkBAT6uIG14AKw0",
 "wbUserId": 12605391,
 "wbUserDetails": {"name": "Елена", "country": "RU", "hasPhoto": false},
 "imtId": 9050224,
 "nmId": 13445937,
 "subjectId": 1724,
 "text": "На свой 52-54 взяла L, сидит хорошо, даже свободненько, худи тёплое и непродуваемое, очень удобное, швы ровные,
  внутренний ворс на одежде не остаётся (носила под худи футболку)", 

 "pros": "",
 "cons": "", 
 "isObscene": false,
 "matchingSize": "ok",
 "matchingPhoto": "full", 
 "matchingDescription": "full", 
 "visibility": "all",
 "productValuation": 5, 
 "color": "коричневый", 
 "size": "L", 
 "createdDate": "2021-04-28T17:30:13Z", 
 "updatedDate": "2021-04-28T20:28:51Z", 
 "answer": null, "state": "none", 
 "productDetails": {"imtId": 9050224, 
                    "nmId": 13445937, 
                    "productName": "Худи", 
                    "supplierArticle": "оверхудижен/коричневый",
                    "supplierId": 44090, 
                    "supplierName": "Общество с ограниченной ответственностью \"ХРБ\"", 
                    "brandId": 60295, 
                    "brandName":  "Raven."},
 "metadata": null, 
 "defectType": "none", 
 "problem": null, 
 "feedbackHelpfulness": [{"wbUserId": 52810658, "helpfulness": "plus", "time": "2021-04-28T20:28:51Z"}],
 "photos": null,
 "video": null,
 "rank": 0.2049397714725764,
 "votes": {"pluses": 1, "minuses": 0}}
